"""
Post-execution guardrails for inspecting output generated by LLMs before returning to users.
Includes comprehensive PII/secret scrubbing and claim-level factual grounding verification.
"""

import re
from typing import Any, Dict, List, Set, Tuple, Optional


class GroundingResult(tuple):
    """2-tuple (is_grounded, score) with ungrounded_claims property for backward-compatibility."""
    def __new__(cls, is_grounded: bool, score: float, ungrounded_claims: Optional[List[str]] = None):
        obj = super().__new__(cls, (is_grounded, score))
        obj.is_grounded = is_grounded
        obj.score = score
        obj.ungrounded_claims = ungrounded_claims or []
        return obj

    def __iter__(self):
        return iter((self.is_grounded, self.score))


class PostExecutionGuardrail:
    PII_PATTERNS = {
        "OPENAI_KEY": r"\bsk-[A-Za-z0-9_-]{20,}\b",
        "BEARER_TOKEN": r"\bBearer\s+[A-Za-z0-9_\-\.]{20,}\b",
        "GITHUB_TOKEN": r"\bgh[pousr]_[A-Za-z0-9]{36,}\b",
        "GOOGLE_API_KEY": r"\bAIza[0-9A-Za-z-_]{35}\b",
        "AWS_ACCESS_KEY": r"\bAKIA[0-9A-Z]{16}\b",
        "SSN": r"\b\d{3}-\d{2}-\d{4}\b",
        "CREDIT_CARD_VISA": r"\b4[0-9]{12}(?:[0-9]{3})?\b",
        "CREDIT_CARD_MASTERCARD": r"\b5[1-5][0-9]{14}\b",
        "CREDIT_CARD_AMEX": r"\b3[47][0-9]{13}\b",
        "CREDIT_CARD_DISCOVER": r"\b6(?:011|5[0-9]{2})[0-9]{12}\b",
        "CREDIT_CARD_GENERIC": r"\b(?:\d{4}[-\s]?){3}\d{4}\b",
        "EMAIL": r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
        "PHONE_NUMBER": r"\b(?:\+?\d{1,3}[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b",
        "IPV4_ADDRESS": r"\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b",
        "IPV6_ADDRESS": r"\b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\b",
    }

    @classmethod
    def sanitize_pii(cls, text: str) -> str:
        if not text:
            return text

        sanitized = text
        sanitized = re.sub(cls.PII_PATTERNS["OPENAI_KEY"], "[REDACTED_API_KEY]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["BEARER_TOKEN"], "Bearer [REDACTED_TOKEN]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["GITHUB_TOKEN"], "[REDACTED_GITHUB_TOKEN]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["GOOGLE_API_KEY"], "[REDACTED_GOOGLE_API_KEY]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["AWS_ACCESS_KEY"], "[REDACTED_AWS_KEY]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["SSN"], "[REDACTED_SSN]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["CREDIT_CARD_VISA"], "[REDACTED_CARD]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["CREDIT_CARD_MASTERCARD"], "[REDACTED_CARD]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["CREDIT_CARD_AMEX"], "[REDACTED_CARD]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["CREDIT_CARD_DISCOVER"], "[REDACTED_CARD]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["CREDIT_CARD_GENERIC"], "[REDACTED_CARD]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["EMAIL"], "[REDACTED_EMAIL]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["PHONE_NUMBER"], "[REDACTED_PHONE]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["IPV4_ADDRESS"], "[REDACTED_IP]", sanitized)
        sanitized = re.sub(cls.PII_PATTERNS["IPV6_ADDRESS"], "[REDACTED_IPV6]", sanitized)
        return sanitized

    @classmethod
    def _tokenize(cls, text: str) -> Set[str]:
        stop_words = {
            "a", "an", "and", "are", "as", "at", "be", "by", "for", "from",
            "has", "he", "in", "is", "it", "its", "of", "on", "that", "the",
            "to", "was", "were", "will", "with", "this", "there", "these", "those"
        }
        words = re.findall(r"\b[a-zA-Z0-9_-]+\b", text.lower())
        return {w for w in words if len(w) > 2 and w not in stop_words}

    @classmethod
    def verify_factual_grounding(
        cls,
        answer: str,
        context_chunks: List[Dict[str, Any]],
        threshold: float = 0.20
    ) -> GroundingResult:
        if not answer or not answer.strip():
            return GroundingResult(True, 1.0, [])

        context_texts = []
        for chunk in (context_chunks or []):
            if isinstance(chunk, dict):
                context_texts.append(chunk.get("content", "") or chunk.get("text", ""))
            elif isinstance(chunk, str):
                context_texts.append(chunk)

        full_context_text = " ".join(context_texts)
        context_tokens = cls._tokenize(full_context_text)

        if not context_tokens:
            claims = [c.strip() for c in re.split(r"(?<=[.!?])\s+", answer) if c.strip()]
            return GroundingResult(False, 0.0, claims)

        raw_claims = [c.strip() for c in re.split(r"(?<=[.!?])\s+", answer) if c.strip()]
        if not raw_claims:
            return GroundingResult(True, 1.0, [])

        grounded_count = 0
        ungrounded_claims: List[str] = []

        for claim in raw_claims:
            claim_tokens = cls._tokenize(claim)
            if not claim_tokens:
                grounded_count += 1
                continue

            overlap = claim_tokens.intersection(context_tokens)
            overlap_ratio = len(overlap) / len(claim_tokens)

            if overlap_ratio >= 0.20:
                grounded_count += 1
            else:
                ungrounded_claims.append(claim)

        grounding_score = grounded_count / len(raw_claims)
        is_grounded = grounding_score >= threshold

        return GroundingResult(is_grounded, round(grounding_score, 3), ungrounded_claims)


# Module-level convenience functions
def sanitize_pii(text: str) -> str:
    return PostExecutionGuardrail.sanitize_pii(text)

def verify_factual_grounding(
    answer: str,
    context_chunks: List[Dict[str, Any]],
    threshold: float = 0.20
) -> GroundingResult:
    return PostExecutionGuardrail.verify_factual_grounding(answer, context_chunks, threshold=threshold)

